# Generated by Django 5.0.7 on 2024-08-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiImport', '0002_rename_year_importdatamodel_ano_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='importdatamodel',
            unique_together={('ncm', 'ano', 'mes', 'pais', 'estado')},
        ),
        migrations.RemoveField(
            model_name='importdatamodel',
            name='unique_field',
        ),
    ]
