# Generated by Django 5.0.7 on 2024-08-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiCommon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestfile',
            name='last_month',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='latestfile',
            name='last_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
