# Generated by Django 5.0.7 on 2024-08-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiCommon', '0002_latestfile_last_month_latestfile_last_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestfile',
            name='file_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
