# Generated by Django 3.2.25 on 2024-07-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_test_user',
            field=models.BooleanField(default=False),
        ),
    ]
