# Generated by Django 3.2.25 on 2024-07-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20240711_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='serial',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
