# Generated by Django 3.2.25 on 2024-07-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20240716_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterField(
            model_name='company',
            name='serial',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
