# Generated by Django 3.2.25 on 2024-07-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20240719_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(default='jubart_default', max_length=255),
            preserve_default=False,
        ),
    ]
