# Generated by Django 3.2.25 on 2024-07-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_company_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='company',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Código da Empresa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome da Empresa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='company',
            name='serial',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Serial'),
        ),
    ]
