# Generated by Django 3.2.25 on 2024-07-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20240719_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_code',
            field=models.CharField(default='e0fe095408da44be8b4e149f5a2679ee', max_length=255, unique=True),
        ),
    ]
