# Generated by Django 3.2.25 on 2024-07-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_profile_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
